#!/bin/bash
#to check if a file exists

filename="test.sh"

if [ -f "$filename" ]; then
	echo "The file is exists"
	exit 200
	echo $?
else 
	echo "The file does not exist"
	exit 201
	echo $?

fi



#i. we can check if the correct exit code is generated by using echo$?
#ii. if the command is place after the if block, you will see the exit code as 201 as the command executes the exit code for the last command executed.
#iii. if the command is placed directly after the exit command we do not get a result as the file already exits the loop.
